[package]
name = "cmark"
version = "0.1.0"
edition = "2024"

[lib]

[features]
flow = []
frontmatter = []

[dependencies]
log = "0.4.27"
common = { path = "../common" }
cmark_macros = { path = "../cmark_macros" }